# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestopenbaidu():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testopenbaidu(self):
    self.driver.get("https://www.baidu.com/")
    self.driver.set_window_size(665, 691)
    self.driver.find_element(By.ID, "kw").click()
    self.driver.find_element(By.ID, "kw").send_keys("wulc")
    self.driver.find_element(By.CSS_SELECTOR, ".bdsug-s").click()
    self.driver.find_element(By.LINK_TEXT, "乌龙茶(中国茶叶品种之一)_百度百科").click()
  
